# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('url', models.TextField()),
                ('img_small', models.ImageField(upload_to='clients')),
                ('img_large', models.ImageField(height_field='height_field', upload_to='clients', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('widht_field', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to='')),
            ],
        ),
    ]
