# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creando_app', '0002_auto_20160920_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='url',
            field=models.CharField(max_length=140),
        ),
    ]
