# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 05:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creando_app', '0003_auto_20160920_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='client',
            name='widht_field',
        ),
    ]
