# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creando_app', '0004_auto_20160920_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='widht_field',
            field=models.IntegerField(default=0),
        ),
    ]
