# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 07:06
from __future__ import unicode_literals

import creando_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creando_app', '0006_auto_20160920_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='img_large',
            field=models.ImageField(height_field='height_field', upload_to=creando_app.models.upload_location, width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='client',
            name='img_small',
            field=models.ImageField(height_field='height_field', upload_to=creando_app.models.upload_location, width_field='width_field'),
        ),
    ]
