# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 00:19
from __future__ import unicode_literals

import creando_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creando_app', '0007_auto_20160920_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='client',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='client',
            name='width_field',
        ),
        migrations.AddField(
            model_name='client',
            name='order',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='url_address',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='img_large',
            field=models.ImageField(upload_to=creando_app.models.upload_location),
        ),
        migrations.AlterField(
            model_name='client',
            name='img_small',
            field=models.ImageField(upload_to=creando_app.models.upload_location),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='url',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
